name: Tests
on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.3

      - name: Install tools
        run: |
          python -m pip install --upgrade pip pytest
          pip install coverage
          pip install -r requirements.txt

      - name: Test webpages
        run: python3 tests/test_app.py

      - name: Test investment form
        run: python3 tests/test_form.py
     
      - name: Test alpha vantage
        run: python3 tests/test_alpha_vantage.py
    
      - name: Code coverage report  # Ask Elizabeth about combining coverage reports
        run: |
          python3 -m coverage run -m unittest tests/test_app.py tests/test_form.py tests/test_alpha_vantage.py
          python3 -m coverage report
          python3 -m coverage html
